/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jPaqInterfazMenuCliente;


import jPaqConsultasSQL.ConsultasSQLClienteReporte;
import jPaqDiseno.Diseno;
import jPaqExcepcion.Excepcion;
import jPaqGenerarPDF.PDF;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.table.DefaultTableModel;


public class GuiReporte extends javax.swing.JFrame {
    private final Excepcion objException = new Excepcion();
    ConsultasSQLClienteReporte objClienteReporte;

    /**
     * Creates new form GuiReporte
     */
    public GuiReporte() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTCrudReportes = new javax.swing.JTabbedPane();
        jPListarReporte = new Diseno();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTBListarReporte = new javax.swing.JTable();
        jTReportePlaca = new javax.swing.JTextField();
        jBTBuscarReportePlaca = new javax.swing.JButton();
        jBTBuscarReportePDF = new javax.swing.JButton();
        jPSalirReporte = new javax.swing.JPanel();
        jBTSalirReportes = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        setUndecorated(true);

        jTCrudReportes.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "LISTAR-REPORTE-VEHICULO", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI Black", 1, 18))); // NOI18N

        jTBListarReporte.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTBListarReporte);

        jTReportePlaca.setBackground(new java.awt.Color(246, 246, 246));
        jTReportePlaca.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jTReportePlaca.setForeground(new java.awt.Color(102, 102, 102));
        jTReportePlaca.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTReportePlaca.setText("FILTRAR POR PLACA");
        jTReportePlaca.setAutoscrolls(false);
        jTReportePlaca.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTReportePlacaMouseClicked(evt);
            }
        });
        jTReportePlaca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTReportePlacaActionPerformed(evt);
            }
        });

        jBTBuscarReportePlaca.setBackground(new java.awt.Color(246, 246, 246));
        jBTBuscarReportePlaca.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jBTBuscarReportePlaca.setForeground(new java.awt.Color(102, 102, 102));
        jBTBuscarReportePlaca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jPaqImagenes/placa.png"))); // NOI18N
        jBTBuscarReportePlaca.setToolTipText("");
        jBTBuscarReportePlaca.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jBTBuscarReportePlaca.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        jBTBuscarReportePlaca.setIconTextGap(40);
        jBTBuscarReportePlaca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBTBuscarReportePlacaActionPerformed(evt);
            }
        });

        jBTBuscarReportePDF.setBackground(new java.awt.Color(246, 246, 246));
        jBTBuscarReportePDF.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jBTBuscarReportePDF.setForeground(new java.awt.Color(102, 102, 102));
        jBTBuscarReportePDF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jPaqImagenes/pdf.png"))); // NOI18N
        jBTBuscarReportePDF.setToolTipText("");
        jBTBuscarReportePDF.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jBTBuscarReportePDF.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        jBTBuscarReportePDF.setIconTextGap(40);
        jBTBuscarReportePDF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBTBuscarReportePDFActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPListarReporteLayout = new javax.swing.GroupLayout(jPListarReporte);
        jPListarReporte.setLayout(jPListarReporteLayout);
        jPListarReporteLayout.setHorizontalGroup(
            jPListarReporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPListarReporteLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPListarReporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPListarReporteLayout.createSequentialGroup()
                        .addComponent(jBTBuscarReportePlaca, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTReportePlaca, javax.swing.GroupLayout.PREFERRED_SIZE, 534, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBTBuscarReportePDF, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 732, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44))
        );
        jPListarReporteLayout.setVerticalGroup(
            jPListarReporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPListarReporteLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPListarReporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPListarReporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jTReportePlaca)
                        .addComponent(jBTBuscarReportePlaca, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jBTBuscarReportePDF, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 466, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jTCrudReportes.addTab("LISTAR REPORTE DE VEHICULOS", jPListarReporte);

        jBTSalirReportes.setBackground(new java.awt.Color(255, 51, 51));
        jBTSalirReportes.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jBTSalirReportes.setForeground(new java.awt.Color(102, 102, 102));
        jBTSalirReportes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jPaqImagenes/salir.png"))); // NOI18N
        jBTSalirReportes.setText("CERRAR LISTA DE REPORTES");
        jBTSalirReportes.setToolTipText("");
        jBTSalirReportes.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jBTSalirReportes.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        jBTSalirReportes.setIconTextGap(40);
        jBTSalirReportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBTSalirReportesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPSalirReporteLayout = new javax.swing.GroupLayout(jPSalirReporte);
        jPSalirReporte.setLayout(jPSalirReporteLayout);
        jPSalirReporteLayout.setHorizontalGroup(
            jPSalirReporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPSalirReporteLayout.createSequentialGroup()
                .addGap(174, 174, 174)
                .addComponent(jBTSalirReportes)
                .addContainerGap(221, Short.MAX_VALUE))
        );
        jPSalirReporteLayout.setVerticalGroup(
            jPSalirReporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPSalirReporteLayout.createSequentialGroup()
                .addGap(204, 204, 204)
                .addComponent(jBTSalirReportes, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(314, Short.MAX_VALUE))
        );

        jTCrudReportes.addTab("SALIR", jPSalirReporte);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jTCrudReportes, javax.swing.GroupLayout.PREFERRED_SIZE, 825, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(41, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addComponent(jTCrudReportes, javax.swing.GroupLayout.PREFERRED_SIZE, 666, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBTSalirReportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBTSalirReportesActionPerformed
        dispose();
    }//GEN-LAST:event_jBTSalirReportesActionPerformed

    private void jTReportePlacaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTReportePlacaMouseClicked
        jTReportePlaca.setText("");
    }//GEN-LAST:event_jTReportePlacaMouseClicked

    private void jTReportePlacaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTReportePlacaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTReportePlacaActionPerformed

    private void jBTBuscarReportePlacaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBTBuscarReportePlacaActionPerformed
        objClienteReporte = new ConsultasSQLClienteReporte();
        jTReportePlaca.setText(jTReportePlaca.getText().toUpperCase());
        if ((jTReportePlaca.getText().equals("")) || (jTReportePlaca.getText().equals("FILTRAR POR PLACA"))) {
            jTReportePlaca.setText("FILTRAR POR PLACA");
            mostrarMatriz(objClienteReporte.reporteES(""));
        }else {
            mostrarMatriz(objClienteReporte.reporteES(jTReportePlaca.getText()));
        }
    }//GEN-LAST:event_jBTBuscarReportePlacaActionPerformed

    private void jBTBuscarReportePDFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBTBuscarReportePDFActionPerformed
        PDF objPDF = new PDF();
        objClienteReporte = new ConsultasSQLClienteReporte();
        jTReportePlaca.setText(jTReportePlaca.getText().toUpperCase());
        if ((jTReportePlaca.getText().equals("")) || (jTReportePlaca.getText().equals("FILTRAR POR PLACA"))) {
            jTReportePlaca.setText("FILTRAR POR PLACA");
            String varTitulo = "REPORTE DE TODAS LAS FACTURAS";
            String varRuta = "\\Desktop\\PROYECTO FINAL DESARROLO 1\\proyecto desarrolado en java y xampp\\ReporteTotal.pdf";
            if (objPDF.gemerarPDF(objClienteReporte.reporteES(""), varTitulo, varRuta)){
                objException.excepcionGuardado(0, "REPORTE  REALIZADO");
            }else{
                objException.excepcionGuardado(1, "INCONVENIENTE CON EL REPORTE");
            }
        }else {
            String varTitulo = "REPORTE POR PLACA ("+jTReportePlaca.getText()+") ";
            String varRuta = "\\Desktop\\PROYECTO FINAL DESARROLO 1\\proyecto desarrolado en java y xampp\\ReportePlaca.pdf";
            if (objPDF.gemerarPDF(objClienteReporte.reporteES(jTReportePlaca.getText()), varTitulo, varRuta)){
                objException.excepcionGuardado(0, "REPORTE  REALIZADO");
            }else{
                 objException.excepcionGuardado(1, "INCONVENIENTE CON EL REPORTE");
            }
        }
    }//GEN-LAST:event_jBTBuscarReportePDFActionPerformed

    public void mostrarMatriz(String varMatriz[][]) {
        DefaultTableModel objModel = (DefaultTableModel) jTBListarReporte.getModel();
        objModel.setRowCount(varMatriz.length);
        objModel.setColumnCount(7);
        jTBListarReporte.getColumn("A").setHeaderValue("CODIGO FACTURA");
        jTBListarReporte.getColumn("B").setHeaderValue("PLACA");
        jTBListarReporte.getColumn("C").setHeaderValue("VEHICULO");
        jTBListarReporte.getColumn("D").setHeaderValue("COSTO");
        jTBListarReporte.getColumn("E").setHeaderValue("HORA DE INGRESO");
        jTBListarReporte.getColumn("F").setHeaderValue("HORA DE SALIDA");
        jTBListarReporte.getColumn("G").setHeaderValue("FECHA REGISTRO");
        for (int i = 0; i < varMatriz.length; i++) {
            for (int j = 0; j < 7; j++) {
                jTBListarReporte.setValueAt(varMatriz[i][j], i, j);
            }
        }
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GuiReporte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GuiReporte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GuiReporte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GuiReporte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GuiReporte().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBTBuscarReportePDF;
    private javax.swing.JButton jBTBuscarReportePlaca;
    private javax.swing.JButton jBTSalirReportes;
    private javax.swing.JPanel jPListarReporte;
    private javax.swing.JPanel jPSalirReporte;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTBListarReporte;
    private javax.swing.JTabbedPane jTCrudReportes;
    private javax.swing.JTextField jTReportePlaca;
    // End of variables declaration//GEN-END:variables
     @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().
                getImage(ClassLoader.getSystemResource("jPaqImagenes/coche.png"));
        return retValue;
    }

}
